test = {   'name': 'q3',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> test_bc[1]\n0.0',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> test_bc[6]\n2.0',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
