test = {   'name': 'q5',
    'points': 2,
    'suites': [   {   'cases': [   {   'code': '>>> moc_data.num_rows\n519',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> moc_data.num_columns\n31',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
